### ISSUE TITLE
http_client hangs when exiting on GCC with C++1[14] enabled

### ISSUE THREAD

**Issue by el-bart** [cpp-netlib/cpp-netlib#488]
on GCC-4.9 with C++11 or C++14 enabled, when using following test application (simplified http_client1.cpp):

```cpp
#include <iostream>
#include <boost/network/protocol/http/client.hpp>
using namespace boost::network;

int main()
{
  http::client client;
  http::client::request request("http://www.google.com");
  request << header("Connection", "close");
  http::client::response response = client.get(request);
  std::cout << body(response) << std::endl;
  std::cout << "this text is always visible" << std::endl;
}
```

program always hangs when exiting. last visible message is "this text is always visible". then it hangs forever. stack traces follow:

```
(gdb) info threads
  Id   Target Id         Frame 
  3    Thread 0x7ffff1d22700 (LWP 23730) "a.out" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff2829700 (LWP 23729) "a.out" 0x00007ffff59822a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7ffff7fb87c0 (LWP 23725) "a.out" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6f401ad in pthread_cond_wait () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#2  0x0000000000416257 in boost::condition_variable::wait (this=0x61500000f858, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#3  0x00007ffff68965ac in boost::thread::join_noexcept() () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#4  0x00000000004187fe in boost::thread::join (this=0x60200000ef70) at /usr/include/boost/thread/detail/thread.hpp:756
#5  0x0000000000447f75 in boost::network::http::impl::async_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~async_client (this=0x61200000bd40, __in_chrg=<optimized out>)
    at /usr/include/boost/network/protocol/http/client/async_impl.hpp:67
#6  0x0000000000454a8c in boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client_impl (this=0x61200000bd40, __in_chrg=<optimized out>)
    at /usr/include/boost/network/protocol/http/client/pimpl.hpp:79
#7  0x0000000000452533 in boost::checked_delete<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> > (x=0x61200000bd40) at /usr/include/boost/checked_delete.hpp:34
#8  0x00000000004611bb in boost::detail::sp_counted_impl_p<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> >::dispose (this=0x603000028420)
    at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:78
#9  0x00000000004138ad in boost::detail::sp_counted_base::release (this=0x603000028420) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#10 0x0000000000413a34 in boost::detail::shared_count::~shared_count (this=0x7fffffffdfe8, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:371
#11 0x0000000000423bf6 in boost::shared_ptr<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> >::~shared_ptr (this=0x7fffffffdfe0, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:328
#12 0x0000000000423c10 in boost::network::http::basic_client_facade<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client_facade (this=0x7fffffffdfe0, __in_chrg=<optimized out>)
    at /usr/include/boost/network/protocol/http/client/facade.hpp:26
#13 0x0000000000423c2a in boost::network::http::basic_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client (this=0x7fffffffdfe0, __in_chrg=<optimized out>)
    at /usr/include/boost/network/protocol/http/client.hpp:33
#14 0x000000000041136b in main () at err.cpp:12
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff2829700 (LWP 23729))]
#0  0x00007ffff59822a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff59822a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000041e1d0 in boost::asio::detail::epoll_reactor::run (this=0x60f00001de60, block=true, ops=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x000000000041ffc3 in boost::asio::detail::task_io_service::do_run_one (this=0x60f00000ed70, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:368
#3  0x000000000041f54f in boost::asio::detail::task_io_service::run (this=0x60f00000ed70, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#4  0x000000000042098d in boost::asio::io_service::run (this=0x60400000d5b0) at /usr/include/boost/asio/impl/io_service.ipp:59
#5  0x000000000046d9ee in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator() (this=0x61500000f9b8, p=0x60400000d5b0) at /usr/include/boost/bind/mem_fn_template.hpp:49
#6  0x000000000046a167 in boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0> (this=0x61500000f9c8, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:243
#7  0x0000000000464715 in boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator() (this=0x61500000f9b8)
    at /usr/include/boost/bind/bind_template.hpp:20
#8  0x000000000046107a in boost::detail::thread_data<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run (
    this=0x61500000f800) at /usr/include/boost/thread/detail/thread.hpp:117
#9  0x00007ffff6895aea in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#10 0x00007ffff646f0a4 in start_thread (arg=0x7ffff2829700) at pthread_create.c:309
#11 0x00007ffff5981ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 3
[Switching to thread 3 (Thread 0x7ffff1d22700 (LWP 23730))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6f401ad in pthread_cond_wait () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#2  0x000000000042b5cc in boost::asio::detail::posix_event::wait<boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex> > (this=0x7ffff1d21c60, lock=...) at /usr/include/boost/asio/detail/posix_event.hpp:80
#3  0x0000000000420210 in boost::asio::detail::task_io_service::do_run_one (this=0x60f00000ec80, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:395
#4  0x000000000041f54f in boost::asio::detail::task_io_service::run (this=0x60f00000ec80, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#5  0x000000000042098d in boost::asio::io_service::run (this=0x60200000eff0) at /usr/include/boost/asio/impl/io_service.ipp:59
#6  0x0000000000421dee in boost::asio::detail::resolver_service_base::work_io_service_runner::operator() (this=0x60200000ef18) at /usr/include/boost/asio/detail/impl/resolver_service_base.ipp:32
#7  0x00000000004632fe in boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_io_service_runner>::run (this=0x60200000ef10) at /usr/include/boost/asio/detail/posix_thread.hpp:82
#8  0x0000000000421cef in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=0x60200000ef10) at /usr/include/boost/asio/detail/impl/posix_thread.ipp:64
#9  0x00007ffff646f0a4 in start_thread (arg=0x7ffff1d22700) at pthread_create.c:309
#10 0x00007ffff5981ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

problem occuress only when compiling with GCC (with or without optimizations or debug info) and having C++11 or C++14 standard version enabled. if no "-std=xxx" flag is given, everything works fine. when using clang, all 3 standards work fine.

i'm using debian/testing with all packages directly from distribution, that is:
  * cpp-netlib 0.11.0
  * g++ 4.9.1
  * clang++ 3.5
  * boost 1.55

**Comment by mikhailberis** [comment]
This one's interesting. Can you try 0.11.1? You can get it from
http://cpp-netlib.org/

**Comment by el-bart** [comment]
yup - 0.11.1 solved the problem. looks like i'll need to use my own compilation until package is updated in debian. sorry for bothering.

btw: during compilation i found 2 warnings - reported as #489.
