### ISSUE TITLE
boost::network::uri segmentation fault on invalid port part of uri

### ISSUE THREAD

**Issue by tex** [cpp-netlib/cpp-netlib#791]
On `master` branch, the following
```
    network::uri root("http://www.somehost.comfrf.fwe:://wfef");
```
causes segmentation fault when used by client (shouldn't it throw network::uri_syntax_error instead?):

```
0x00007ffff5f9fb25 in ____strtoull_l_internal () from /nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5f9fb25 in ____strtoull_l_internal () from /nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libc.so.6
#1  0x00000000006bcff9 in network::uri::port<unsigned short> (this=0x7fffffff3360)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/network/uri/uri.hpp:314
#2  0x00000000006b948d in boost::network::http::impl::port_wrapper<boost::network::http::tags::http_default_8bit_udp_resolve>::operator boost::optional<unsigned short> (this=0x7fffffff2cb8)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/message/wrappers/port.hpp:45
#3  0x00000000006b352b in boost::network::http::linearize<boost::network::http::basic_request<boost::network::http::tags::http_default_8bit_udp_resolve>, std::ostreambuf_iterator<char, std::char_traits<char> > > (request=..., method=..., version_major=1, 
    version_minor=1, oi=...)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/algorithms/linearize.hpp:142
#4  0x00000000006aea22 in boost::network::http::impl::http_async_connection<boost::network::http::tags::http_default_8bit_udp_resolve, 1u, 1u>::start(boost::network::http::basic_request<boost::network::http::tags::http_default_8bit_udp_resolve> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::function<void (boost::iterator_range<char const*> const&, boost::system::error_code const&)>, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>) (this=0x9d1400, request=..., method=..., get_body=true, callback=..., generator=...)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/client/connection/async_normal.hpp:172
#5  0x000000000068a56d in boost::network::http::async_connection_policy<boost::network::http::tags::http_default_8bit_udp_resolve, 1u, 1u>::connection_impl::send_request(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::network::http::basic_request<boost::network::http::tags::http_default_8bit_udp_resolve> const&, bool, std::function<void (boost::iterator_range<char const*> const&, boost::system::error_code const&)>, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>) (this=0x9d13a0, method=..., request_=..., get_body=true, callback=..., generator=...)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/policies/async_connection.hpp:60
#6  0x000000000068262d in boost::network::http::impl::async_client<boost::network::http::tags::http_default_8bit_udp_resolve, 1u, 1u>::request_skeleton(boost::network::http::basic_request<boost::network::http::tags::http_default_8bit_udp_resolve> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::function<void (boost::iterator_range<char const*> const&, boost::system::error_code const&)>, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>) (this=0x9d04e0, request_=..., method=..., get_body=true, callback=..., generator=...)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/client/async_impl.hpp:90
#7  0x00000000006787c0 in boost::network::http::basic_client_facade<boost::network::http::tags::http_default_8bit_udp_resolve, 1u, 1u>::get(boost::network::http::basic_request<boost::network::http::tags::http_default_8bit_udp_resolve> const&, std::function<void (boost::iterator_range<char const*> const&, boost::system::error_code const&)>) (this=0x7fffffff3440, request=..., body_handler=...)
    at /home/milan/dev/cpp/wc/install/cpp-netlib/include/boost/network/protocol/http/client/facade.hpp:85
```

**Comment by deanberris** [comment]
It looks like this can also be fixed in the implementation of linearize. Although I agree with you that this seems like a bug in the URI library implementation.
