### ISSUE TITLE
SIGSEGV async server 0.13-release, boost-1.65

### ISSUE THREAD

**Issue by tex** [cpp-netlib/cpp-netlib#807]
```
class server {
public:
  server()
      : options_(handler_),
        server_(
            options_.address("0.0.0.0")
                .port("8000")
                .reuse_address(true)
                .thread_pool(
                    std::make_shared<boost::network::utils::thread_pool>(1))) {
    std::thread t([this] { this->server_.run(); });
    t.detach();
  }

  virtual ~server() { server_.stop(); }

private:
  struct handler;
  using http_server = boost::network::http::server<server::handler>;

  struct handler {
    void operator()(http_server::request const &request,
                    http_server::connection_ptr connection) {
...
    }
  };

  handler handler_;
  http_server::options options_;
  http_server server_;
};




Thread 7 "TutorialTest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5227700 (LWP 11335)]
boost::asio::detail::epoll_reactor::run (this=0x0, block=true, ops=...) at include/boost/asio/detail/impl/epoll_reactor.ipp:428
428     include/boost/asio/detail/impl/epoll_reactor.ipp: No such file or directory.
(gdb) bt
#0  boost::asio::detail::epoll_reactor::run (this=0x0, block=true, ops=...) at include/boost/asio/detail/impl/epoll_reactor.ipp:428
#1  0x00000000005a6c78 in boost::asio::detail::task_io_service::do_run_one (this=0xa25370, lock=..., this_thread=..., ec=...)
    at include/boost/asio/detail/impl/task_io_service.ipp:356
#2  0x00000000005a69a1 in boost::asio::detail::task_io_service::run (this=0xa25370, ec=...)
    at include/boost/asio/detail/impl/task_io_service.ipp:149
#3  0x00000000005a9ca1 in boost::asio::io_service::run (this=0xa229c0) at include/boost/asio/impl/io_service.ipp:59
#4  boost::network::http::async_server_base<boost::network::http::tags::http_server, server::handler>::run (this=<optimized out>)
    at /home/milan/dev/cpp/wc/build/install/cpp-netlib/include/boost/network/protocol/http/server/async_server.hpp:80
#5  0x00000000006e7b7f in execute_native_thread_routine ()
#6  0x00007ffff7bc12a5 in start_thread () from /nix/store/asz8g320r00flkzr1biyh83hr3faqxna-glibc-2.26-75/lib/libpthread.so.0
#7  0x00007ffff62a38af in clone () from /nix/store/asz8g320r00flkzr1biyh83hr3faqxna-glibc-2.26-75/lib/libc.so.6
```

**Comment by carun** [comment]
@tex what was the root cause? It could help someone else in future when they refer to this.

**Comment by tex** [comment]
Well, I changed my code to this and I'm unable to reproduce the issue.
(So I considered it my problem, therefore closed issue. But I agree that cpp-netlib really lacks detailed and complete and working examples / documentation describing not only simplest use case)

```
class server {
public:
  server() : options_(handler_) {

    server_ = std::make_shared<http_server>(
        options_.address("0.0.0.0")
            .port("8000")
            .reuse_address(true)
            .thread_pool(
                std::make_shared<boost::network::utils::thread_pool>(5)));

    thread_ =
        std::make_unique<std::thread>([&server_ = server_] { server_->run(); });

    // Give some time to thread_ and server_ to initialize.
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
  }

  virtual ~server() {
    server_->stop();
    thread_->join();
  }

  std::unique_ptr<std::thread> thread_;
  handler handler_;
  http_server::options options_;
  std::shared_ptr<http_server> server_;
};
```
